"""removed property from chat_session_model

Revision ID: 1d6b2f9d7b31
Revises: 5a31cf9866b0
Create Date: 2026-07-24 19:50:15.414118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6b2f9d7b31'
down_revision: Union[str, Sequence[str], None] = '5a31cf9866b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
