"""remove video metadata fields

Revision ID: 2525a1659abf
Revises: da9413fe6048
Create Date: 2026-07-18 06:10:22.308141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2525a1659abf'
down_revision: Union[str, Sequence[str], None] = 'da9413fe6048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'last_opened')
    op.drop_column('videos', 'channel')
    op.drop_column('videos', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('channel', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('last_opened', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
