"""removed MessageRetrieval model and username field from user_model

Revision ID: 90f87c838b37
Revises: 6fd6444507da
Create Date: 2026-07-22 10:23:24.831753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90f87c838b37'
down_revision: Union[str, Sequence[str], None] = '6fd6444507da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_retrievals')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_table('message_retrievals',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('retrieved_context', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('retrieved_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_retrievals_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('message_retrievals_pkey'))
    )
    # ### end Alembic commands ###
